# Generated by Django 5.0 on 2024-03-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=30)),
                ('day', models.DateField()),
                ('percentage', models.IntegerField()),
                ('subject', models.CharField(max_length=20)),
                ('roll_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=20)),
                ('marks', models.IntegerField()),
                ('teacher_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('marks', models.IntegerField()),
                ('attend_percent', models.IntegerField()),
                ('subject', models.CharField(max_length=20)),
                ('stud_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('subject', models.CharField(max_length=20)),
                ('period', models.IntegerField()),
                ('cls', models.CharField(max_length=20)),
                ('teacher_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
