# Generated by Django 5.0 on 2024-03-26 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_system', '0002_alter_marks_teacher_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_id',
            new_name='id',
        ),
    ]
