# Generated by Django 5.0 on 2024-03-26 09:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_system', '0003_rename_teacher_id_teacher_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='stud_name',
            new_name='student_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='stud_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='stud_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='marks',
        ),
        migrations.AddField(
            model_name='marks',
            name='student_rn',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='attendance_system.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='percentage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
